---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check if flaresolverr container is running
      community.docker.docker_container_info:
        name: flaresolverr
      register: flaresolverr_info

    - name: Verify flaresolverr container is running
      ansible.builtin.assert:
        that:
          - flaresolverr_info.container.State.Status == "running"
        fail_msg: "flaresolverr container is not running"
        success_msg: "flaresolverr container is running successfully"
