---
namespace: compscidr
name: media_server
authors:
    - Jason Ernst <ernstjason1@gmail.com>
description: A collection of roles for running a media server - sonarr, radarr, plex, ombi, transmission, etc
license_file: LICENSE
readme: README.md
version: 0.0.4
repository: https://github.com/compscidr/ansible-media-server
tags:
    - docker
    - sonarr
    - radarr
    - plex
    - ombi
    - transmission
    - flaresolverr
    - jackett
    - prowlarr
dependencies:
    community.docker: "*"