---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check if prowlarr container is running
      community.docker.docker_container_info:
        name: prowlarr
      register: prowlarr_info

    - name: Verify prowlarr container is running
      ansible.builtin.assert:
        that:
          - prowlarr_info.container.State.Status == "running"
        fail_msg: "prowlarr container is not running"
        success_msg: "prowlarr container is running successfully"

    - name: Verify prowlarr directory exists
      ansible.builtin.stat:
        path: "/tmp/prowlarr"
      register: prowlarr_dir

    - name: Assert prowlarr directory exists
      ansible.builtin.assert:
        that:
          - prowlarr_dir.stat.exists
          - prowlarr_dir.stat.isdir
        fail_msg: "prowlarr directory does not exist"
        success_msg: "prowlarr directory exists"
