---
sonarr_folder: /etc/sonarr
sonarr_tv_folder: /storage/tv
sonarr_tranmissions_downloads_folder: /storage/downloads
sonarr_sabnzbd_downoads_folder: /config/Downloads/complete
sonarr_port: 8989
sonarr_tz: "America/Los_Angeles"
sonarr_pid: "1000"
sonarr_gid: "1000"
