---
# - name: Prereqs
#   hosts: all
#   become: true
#   tasks:
#     - name: Install prereqs
#       ansible.builtin.apt:
#         update_cache: true
#         pkg:
#           - docker.io
#           - sudo

- name: Test the playbook
  ansible.builtin.import_playbook: ../../playbook.yml
