---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        # Media user/group for container PUID/PGID (must exist in container)
        media_user_user: root
        media_user_group: root
        # Base storage path for media folders
        media_storage_base_path: "/tmp/storage"
        # Override defaults for testing - use /tmp for test directories
        plex_folder: "/tmp/plex"
        plex_tv_folder: "/tmp/tv"
        plex_movies_folder: "/tmp/movies"
        plex_music_folder: "/tmp/music"
        ombi_folder: "/tmp/ombi"
        radarr_folder: "/tmp/radarr"
        sonarr_folder: "/tmp/sonarr"
        lidarr_folder: "/tmp/lidarr"
        jackett_folder: "/tmp/jackett"
        prowlarr_folder: "/tmp/prowlarr"
        sabnzbd_folder: "/tmp/sabnzbd"
        transmission_folder: "/tmp/transmission"
        slskd_folder: "/tmp/slskd"
        soularr_folder: "/tmp/soularr"
        # Skip docker installation since we're already running in docker
        install_docker: false
        lidarr_install_docker: false
        sonarr_install_docker: false
        radarr_install_docker: false
        slskd_install_docker: false
        soularr_install_docker: false
        # Set test role from environment variable
        test_role: "{{ lookup('env', 'ANSIBLE_TEST_ROLE') }}"
verifier:
  name: ansible
