---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: /home/runner/work/ansible-media-server/ansible-media-server/roles
  inventory:
    host_vars:
      instance:
        # Override defaults for testing - use /tmp for test directories
        plex_folder: "/tmp/plex"
        plex_tv_folder: "/tmp/tv"
        plex_movies_folder: "/tmp/movies"
        plex_music_folder: "/tmp/music"
verifier:
  name: ansible
