---
name: CI
# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: true
          working_directory: ""
          requirements_file: ""

  molecule-test:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - flaresolverr
          - jackett
          - lidarr
          - ombi
          - plex
          - prowlarr
          - radarr
          - sabnzbd
          - sonarr
          - transmission
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run molecule test for ${{ matrix.role }}
        run: |
          cd roles/${{ matrix.role }}
          molecule test
