name: ansible-lint
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize ]

jobs:
  lint:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        # optional (see below):
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""
        # https://github.com/geerlingguy/ansible-role-redis/blob/master/.github/workflows/ci.yml

  deploy-test:
    runs-on: ubuntu-24.04
    name: Molecule Test
    steps:
      - uses: actions/checkout@v4
      - name: Install and run molecule
        run: |
          python3 -m venv venv 
          . venv/bin/activate
          pip3 install -r requirements.txt
          molecule test
